version: '3.5' 

services:
  backend:
    build: ml-kurkkumopo-backend
    ports:
     - 5000:5000
    volumes:
     - data:/src/model
  frontend:
    build: ml-kurkkumopo-frontend
    ports:
     - 3000:3000
  training:
    build: ml-kurkkumopo-training
    volumes:
     - data:/src/model
     - images:/src/imgs
volumes:
  data:
  images: