version: '3.5' 

services:
  backend:
    build: ml-my-backend
    ports:
     - 5000:5000
    volumes:
     - data:/src/model
  frontend:
    build: ml-my-frontend
    ports:
     - 3000:3000
  training:
    build: ml-my-training
    volumes:
     - data:/src/model
     - images:/src/imgs
volumes:
  data:
  images: