version: '3.5' 

services: 
  proxy:
    image: nginx:latest
    ports: 
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - backend
     - frontend
  backend: 
    image: my-backend
    build: ./back
    ports: 
     - "8000:8000"
    container_name: my-backend
    environment:
     - DB_USERNAME=username
     - DB_PASSWORD=password
     - DB_NAME=mydb
     - DB_HOST=postgres
     - FRONT_URL=http://localhost
  frontend: 
    image: my-frontend
    build: ./front
    ports: 
     - "5000:5000"
    container_name: my-frontend
    environment:
     - API_URL=http://localhost/api
  postgres:
    image: postgres:latest
    ports:
    - "3306:3306"
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=username
    - POSTGRES_DB=mydb